name = input("Hello, whats your name?")
print(name)
board_size = input("Michael, please choose board size:")
print(board_size)
number_of_mines = input("Michael, for board size 9, choose number of mines to allocate:")
print("Michael, the board size is: 9, number of mines is: 7. ENJOY!")
